version: '3'
services:
  api:
    build: api
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: client
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - NODE_ENV=production
      - REACT_APP_FLASK_IP="http://144.91.112.31:5000"

    ports:
      - '3000:80'
    depends_on:
      - api
